### ISSUE TITLE
R parallelization and MAST: any known solutions? 

### ISSUE THREAD

**Issue by eleanorahowe** [RGLab/MAST#78] opened 2017-08-07 14:52 UTC
First I want to thank you folks for writing the MAST package. It's very well-done and has been tremendously useful for my work. Of course I'm writing to ask for advice on how best to use it - in this case for datasets with large numbers of cells.

I have a dataset that has 30,000 cells, and I'd like to do differential expression and GSEA analysis on it. Of course running such a large job on a single core takes a prohibitively long time, so I've taken advantage of MAST's parallelization capacity. This works well for small numbers of cores (~5) but when I expand to larger numbers (10-20) I run into trouble.

This trouble seems to be driven by R's imperfect parallelization, and looks like this: when I run the function bootVcov1 on our large dataset, for example, I specify 10-20 cores using options(mc.cores=20). Assuming the machine has enough memory (an Amazon r4.16xlarge does), this job will spawn 20 processors that briefly spin up to 100% CPU. Then, CPU utilization drops down to some low number like 12% and holds there, and other processes spin up, with names like kworker/migration. The job never finishes because of this low CPU utilization.

From my reading, this is a known problem caused by R's single-threaded statistics libraries. The recommended path to take was to try out Microsoft's r implementation, MRO. I did this, but found that it didn't help with my CPU utilization problem.

So now I'm reaching out to you folks, and wondering if you've had this trouble. How do you work with very large datasets? Have you run into this problem when analyzing many cells? Do you have suggestions for how to make this analysis work?

Thanks very much for your help!

**Comment by gfinak** [comment] 2017-08-07 16:53
Thanks, Elanor
I wonder if you can provide a data set for a reproducible example that we can dig into?
This is definitely an issue we will need to resolve.

**Comment by eleanorahowe** [comment] 2017-08-07 23:12
Yes, I'll put together a dummy example. Thanks much!

**Comment by amcdavid** [comment] 2017-08-09 16:38
Hi Eleanor,

I have also seen similar issues actually resulting from use of multi-threaded linear algebra libraries, such as MRO, in conjunction with fork-level parallelism of R (which what `zlm` uses).  I think these two should work together, but on at least one machine I have access to I have seen deadlocks similar to what you report.

Try setting the environment variables
MKL_NUM_THREADS=1
OPENBLAS_NUM_THREADS=1
OMP_NUM_THREADS=1
to disable multi-threading at the linear algebra level *before* you start R.  If that does any good at least we'll know we are on the right track.

There is a code improvement we could make here too--right now the parallelism happens at the gene level, but it could happen at the bootstrap level.  This would likely be more efficient.

-Andrew

**Comment by eleanorahowe** [comment] 2017-08-12 12:43
Hello folks, 

I've put together a dataset and example code that should illustrate the problem I'm having with parallelizing bootVcov1 and lrtTest/summary. They are run on standard R v3.3.3 on an Amazon EC2 r4.4xlarge instance. More details are in the included example code and session_information files.

Find the (large!) zip file at https://www.dropbox.com/s/w9ywk0ivk9sreij/MAST_parallelization_example.zip?dl=0

The zipfile contains: 
exampleCode.R: The code illustrating the calls you can use to replicate the kworker/migration behavior.
exampleData.rds: an R object holding the dataset used in exampleCode.R.
examplezlm.rds: a pre-computed zlm fit object used by exampleCode.R so you don't have to sit and wait for it to calculate.
hallmarkslist.rds: MSigDb's 50 hallmark genesets, used by exampleCode.R to run GSEA.
session_information.txt: system and R session information about the machine I ran this code on. 
Unzip it all into one directory and run from there. I recommend stepping through the code rather than calling all at once. 

Andrew, I've found I don't have trouble running zlm. It doesn't seem to run in parallel, but it does run to completion so I have few complaints about it. Do you think your environment variable suggestions above would also help with running bootVcov1 and summary? 

Thanks everyone for your input. I look forward to hearing what you think! Please let me know if you have any trouble with the file(s) or have any more questions. 
Eleanor

**Comment by amcdavid** [comment] 2017-08-12 18:24
Hi Eleanor,

Did you try setting those environmental variables?  `zlm` should run in parallel when options(mc.cores>1) and zlm(..., parallel = TRUE)--at the moment those options are the only way you would get a speed up with the bootstrapping.

In any case, I will give your data set a test.  We are interested in making sure MAST can run with the newer versions of SummarizedExperiment which will allow out-of-memory storage of the expression matrix and I need to make sure I am not causing any unnecessary in-memory realizations.

Regards,
Andrew

**Comment by eleanorahowe** [comment] 2017-08-14 18:26
Hello Andrew,

Ok, I've done some tests with those environment variable settings you recommended. I used two different machines, one running "regular" R v3.3.3, Another Canoe, the second running Microsoft R Open v3.4.0. 

For the "regular" R:
Setting the environment variables doesn't seem to affect parallelization of zlm - it still runs on only run processor. It seems to take about the same amount of time to run. 

The environment variables do speed up the fitting to summary/doLRT tremendously - the call took less than 10 minutes to complete, where in the past it has sat running for days. It still results in a ton of those kworker/migration processess, and the cpu utilization is still all over the place, but the job seems to complete in a reasonable amount of time. This is using 30 processors on an m4.16xl instance. 

After the fitting step, though, an error is thrown. I don't know if this error is new or not - I've never gotten this far into the calculation with a dataset of this size before.

> summaryCond <- summary(zlm.fit, doLRT='treatment')
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Refitting on reduced model...
.........................................................................
Done!
Error in o0@loglik - o1@loglik : non-conformable arrays
> traceback()
9: .lrtZlmFit(object, newMM, hypothesis@.Data)
8: lrTest(object, CoefficientHypothesis(x))
7: lrTest(object, CoefficientHypothesis(x))
6: FUN(X[[i]], ...)
5: lapply(doLRT, function(x) lrTest(object, CoefficientHypothesis(x))[,
       , "Pr(>Chisq)"])
4: lapply(doLRT, function(x) lrTest(object, CoefficientHypothesis(x))[,
       , "Pr(>Chisq)"])
3: .local(object, ...)
2: summary(zlm.fit, doLRT = "treatment")
1: summary(zlm.fit, doLRT = "treatment") 

I haven't done any testing with bootv1cov.

For the MRO v3.4.0 machine:

Similarly, I set the environment variables as you suggested and ran my analysis on an m4.16 instance running R 3.4 and Microsoft R Open. Again, zlm doesn't change - it isn't run in parallel and seems to complete single-threaded in a similar amount of time. Also again, summary ran tremendously faster than it has in the past, and the kworker threads still pop up and the cpu utilization of the R threads still go up and down a lot. The job finishes in a very reasonable amount of time -- 5-10 minutes. After the fit, I also see the same non-conformable array error. 

> summaryCond <- summary(zlm.fit, doLRT='treatment')
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Refitting on reduced model...
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Done!
Error in o0@loglik - o1@loglik : non-conformable arrays
> traceback()
9: .lrtZlmFit(object, newMM, hypothesis@.Data)
8: lrTest(object, CoefficientHypothesis(x))
7: lrTest(object, CoefficientHypothesis(x))
6: FUN(X[[i]], ...)
5: lapply(doLRT, function(x) lrTest(object, CoefficientHypothesis(x))[,
       , "Pr(>Chisq)"])
4: lapply(doLRT, function(x) lrTest(object, CoefficientHypothesis(x))[,
       , "Pr(>Chisq)"])
3: .local(object, ...)
2: summary(zlm.fit, doLRT = "treatment")
1: summary(zlm.fit, doLRT = "treatment")


So altogether I'd say that the environment variables have helped a lot, assuming that they aren't the cause of this non-conformable error. Do you folks know how this error is getting generated? Looking at it I don't see where I'm feeding it something inappropriate. I can only assume something about my formula is causing the creation of a badly-proportioned matrix. Any ideas? 

My first thought was that the continuous variable in the formula might be the problem - I had never run one of those before. I recast the data as a two-class factor comparison and re-ran zlm and summary. I got exactly the same error. 

And here's a question that may be totally unrelated to anything but is interesting to me: why does my second summary call (on the MRO machine) produce so many more progress-bar dots than the first one (regular R)? Probably unimportant, but I have to admit I'm curious. The run on regular R produced 74 dots, and the MRO run 1149. Those numbers don't to relate to anything in particular in my mind, but perhaps you guys have an idea.

Thanks so much for your help. I feel like we're getting somewhere!
Eleanor

**Comment by eleanorahowe** [comment] 2017-08-21 15:56
Hello Andrew, Greg, 

Any thoughts on the behavior I'm seeing with MAST now? If you have any ideas for something I could try to fix that crash? Have you been able to replicate it? 

Eleanor

**Comment by amcdavid** [comment] 2017-08-22 23:15
Hi Eleanor,

1.  The crash after calling `summary` looks like a bug that has been fixed in the current version of MAST (now at 1.3.1).  I am investigating to see if using the current version of MAST fixes it (which depends on R 3.4, because Bioconductor depends on R 3.4..sorry).  Are you also getting a crash when you call the bootstrapping?

2. The progress dots are printed every 20 genes by default.  I can't think of a reason why it should be different depending on the R version--maybe the call to `message` is being handled differently by the processes that are forked.

3.  You might turn off saving the residuals (hook=devianceResidualsHook) if you aren't using them--they are mostly responsible for the bloat of`zlm.fit`
```
> library(pryr)
> object_size(zlm.fit)
14.6 GB
> zlm.fit@hookOut = NULL
> object_size(zlm.fit)
5.21 GB
```
(which is basically the size of the data matrix itself, since it is 22966*28248*8 = 4.9 gb)

4.  For bootstrapping, you might give the function MAST:::pbootVcov1 a try.  It parallelizes at a higher level, so should be more efficient.  It's not currently exported, but it is documented.

**Comment by amcdavid** [comment] 2017-08-22 23:18
With regards to memory usage, this is bad behavior https://github.com/RGLab/MAST/blob/ce3ba94ce5e0404331aef1a11d33226f34aaa14a/R/zeroinf.R#L143
I added this call originally because of overhead in calling exprs/assays, but that is probably no longer an issue with SummarizedExperiment (and with a DelayedArray it would force a realization).

**Comment by amcdavid** [comment] 2017-09-05 13:58
Glad to hear things are working better.

RE: GSEA--what command are you using to run the bootstrapping?  If it's `bootVcov1` the threads are likely killed after each bootstrap replication finishes running, which might take about 10 minutes.

RE: `cluster`--that isn't going to work in the context of MAST.  It's specifying a feature particular to the Cox models defined in the survival package, which is an extension beyond the typical GLM that we support.  For clustered observations, we do have some rudimentarily support for mixed effects models, see page nine of  `vignette('MAST-intro')` but I have to say it's somewhat fragile so I can't entirely recommend it to the average user yet.

**Comment by eleanorahowe** [comment] 2017-09-05 15:47
Yes indeed, I'm using bootVcov1. The thread cycling makes sense, then. Thanks!

I'll check out the mixed-effects models. If they're fragile now, do you folks have any plans to make them more robust? I ask because it seems like a very important function to support: I'm of the opinion that we need to treat each cell from a given tissue sample as a repeated measurement on that sample, rather than an independent observation. 

Again, thanks for the help!

**Comment by deveale** [comment] 2017-09-08 22:59
Hi all, 

Thanks for MAST and all the ongoing support, it's done wonders for our research. I believe I'm experiencing an issue that seems similar to the parallelization issue described in this thread and was hoping for some advice on how to alter my configuration to run multiple cores in parallel (or other advice if I'm on the wrong track in trying to resolve the issue). 

With (MAST 1.2.1 / x86_64-apple-darwin15.6.0 (64-bit) / R3.4.1 / data.table_1.10.4 / SummarizedExperiment_1.6.3  / OS X El Capitan 10.11.6), when I call 'summaryCond <- summary(zlmCond, doLRT=CoEfficientName)' with mc.cores>1, it runs nicely. 

On a machine at the lab (currently: MAST 1.3.2 / x86_64, darwin15.6.0 / R 3.4.1 / data.table 1.10.4 / SummarizedExperiment 1.7.5 / OS Sierra 10.12.6 ), it'll run if mc.cores=1, but produces the following error if mc.cores>1: 

"Assertion failure at kmp_runtime.cpp(6480): __kmp_thread_pool == __null.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6480)."

Other searches (https://stat.ethz.ch/pipermail/r-devel/2017-May/074178.html) had me wondering whether the issue with R3.4 or data.table (not sure whether data.table, mcapply or other) manages the threading during this section of the code but since using the same version of data.table in both doesn't resolve the issue, I was wondering if you had other thoughts on how to resolve this (if the issue is with R3.4, sorry!)? thank you for your help, Brian 

**here is more detailed session info for the two environments. please let me know if there is other documentation that would be helpful (https://www.dropbox.com/sh/nzsle98pqn08uyt/AABZ6mNsUZJneQumDYtazMHra?dl=0)

**Comment by amcdavid** [comment] 2017-09-10 20:14
Hi Brian,

We don't make any use of openmp (the library from which kmp_runtime.cpp derives) but I know that data.table has for some time.  Previously on the mac, support was disabled because R was being complied with an ancient version of clang.  Since R 3.4.0 I think this has changed.  Same advice as earlier applies to try setting the environment variable OMP_NUM_THREADS=1 before you start R.  That will disable openmp.  Otherwise I can't help debug this without access to a machine on which it manifests.

**Closed** 2018-02-20 17:44 UTC
